# docker.io/rocm/vllm-dev:rocm6.3.4_navi3x_ubuntu24.04_py3.12_pytorch_2.4_vllm_0.7.2
# FROM rocm/vllm:rocm6.3.1_instinct_vllm0.7.3_20250325
FROM rocm/vllm-dev:nightly_main_20250212
ARG ENTRYPOINT_PATH=image/entrypoint-vllm.sh
# Install basic development tools
RUN apt-get update && apt-get install -y \
    curl jq bsdmainutils bc \
    && rm -rf /var/lib/apt/lists/*

# Install additional dependencies
RUN pip3 install --no-cache-dir \
    transformers \
    accelerate \
    safetensors

# Create non-root user for security
RUN useradd -m -u 2000 vllm
WORKDIR /app
RUN chown vllm:vllm /app

# Create directories for models and benchmarks
RUN mkdir -p /data/benchmarks && \
   chmod 777 /data/benchmarks

# Switch to non-root user
USER vllm

# Make our entrypoint script executable

WORKDIR /
COPY --chown=vllm:vllm ${ENTRYPOINT_PATH} .
RUN chmod +x entrypoint-vllm.sh

WORKDIR /app
ENTRYPOINT ["/entrypoint-vllm.sh"]

# https://rocm.blogs.amd.com/software-tools-optimization/vllm-container/README.html
